---
- name: Install MySQL Server
  apt: pkg={{ item }} state=present
  notify: Restart MySQL
  with_items:
   - mysql-server
   - python-mysqldb

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create MySQL Users
  mysql_user: >
    host={{ item.host|default('localhost') }}
    name={{ item.user }}
    password={{ item.password }}
    priv=*.*:ALL state=present
    login_password={{ mysql_root_password }}
    login_user=root
  notify: Restart MySQL
  with_items: mysql_users

- name: Create Database
  mysql_db: >
    name={{ item.name }}
    state=present
    collation={{ item.collation|default('utf8_general_ci') }}
    encoding={{ item.encoding|default('utf8') }}
    login_host=localhost
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: mysql_databases
